### ISSUE TITLE
Your OAuth token is likely expired

### ISSUE THREAD

**Issue by Noobonprovam** [Delitel-WEB/YandexMusicDiscordBot#1]
Traceback (most recent call last):
  File "C:\Users\ДМИТРИЙ\Downloads\main\main.py", line 3, in <module>
    import bot.interactions
  File "C:\Users\ДМИТРИЙ\Downloads\main\bot\interactions\__init__.py", line 2, in <module>
    from .import music
  File "C:\Users\ДМИТРИЙ\Downloads\main\bot\interactions\music.py", line 3, in <module>
    from ..music.YM.fetch_link import fetch_link
  File "C:\Users\ДМИТРИЙ\Downloads\main\bot\music\__init__.py", line 1, in <module>
    from .voice import GuildsManager
  File "C:\Users\ДМИТРИЙ\Downloads\main\bot\music\voice.py", line 1, in <module>
    from .YM.Track import Track
  File "C:\Users\ДМИТРИЙ\Downloads\main\bot\music\YM\__init__.py", line 5, in <module>
    client = asyncio.run(ClientAsync(YMToken).init())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ДМИТРИЙ\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ДМИТРИЙ\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ДМИТРИЙ\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\ДМИТРИЙ\AppData\Local\Programs\Python\Python311\Lib\site-packages\yandex_music\client_async.py", line 74, in wrapper
    result = await method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ДМИТРИЙ\AppData\Local\Programs\Python\Python311\Lib\site-packages\yandex_music\client_async.py", line 160, in init
    self.me = await self.account_status()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ДМИТРИЙ\AppData\Local\Programs\Python\Python311\Lib\site-packages\yandex_music\client_async.py", line 74, in wrapper
    result = await method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ДМИТРИЙ\AppData\Local\Programs\Python\Python311\Lib\site-packages\yandex_music\client_async.py", line 179, in account_status
    result = await self._request.get(url, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ДМИТРИЙ\AppData\Local\Programs\Python\Python311\Lib\site-packages\yandex_music\utils\request_async.py", line 273, in get
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ДМИТРИЙ\AppData\Local\Programs\Python\Python311\Lib\site-packages\yandex_music\utils\request_async.py", line 241, in _request_wrapper
    raise UnauthorizedError(message)
yandex_music.exceptions.UnauthorizedError: {'name': 'session-expired', 'message': 'Your OAuth token is likely expired'}

**Comment by Delitel-WEB** [comment]
Обновите токен ЯМ
